version: 2
updates:
  - package-ecosystem: npm
    directory: /whatsapp
    schedule:
      interval: daily
    labels:
      - dependencies
      - whatsapp
    commit-message:
      prefix: chore
      include: scope
    allow:
      - dependency-type: direct

  - package-ecosystem: maven
    directory: /timeless-api
    schedule:
      interval: daily
    labels:
      - dependencies
      - backend
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    directory: /timeless-api/src/main/webui
    schedule:
      interval: daily
    labels:
      - dependencies
      - frontend
    commit-message:
      prefix: chore
      include: scope
    allow:
      - dependency-type: direct
