name: Timeless API - Integration Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'timeless-api/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'timeless-api/**'

jobs:
  test:
    name: Run Tests (Testcontainers)
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: timeless-api

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Run Maven Tests
        run: mvn -B -ntp formatter:validate impsort:check verify
